import Hero from "./Hero/Hero"
import Navbar from "./Navbar/Navbar"
import About from "./About/About"
import Skills from "./Skills/Skills"
import Resume from "./Resume/Resume"
import Education from "./Education/Education"
import Projects from "./Projects/Projects"
import Footer from "./Footer/Footer"
import Socials from "./Socials/Socials"
export {Hero,Navbar, About, Skills,Resume,Education,Projects, Footer, Socials}